# Generated by Django 2.2.3 on 2019-07-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190718_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saleOrNot',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
