# Generated by Django 2.2.3 on 2019-08-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190801_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Title',
        ),
    ]
